// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCo2Dc6Zw4nXJywFinu_g4xT2BKzoYHNY',
    appId: '1:209827023192:web:5ac612ea0c156225917d2d',
    messagingSenderId: '209827023192',
    projectId: 'et-si-app',
    authDomain: 'et-si-app.firebaseapp.com',
    storageBucket: 'et-si-app.firebasestorage.app',
    measurementId: 'G-B08WC40SN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YGH_vBDBhaqFxT7nBe4v_z8UtU1gMQU',
    appId: '1:209827023192:android:372ee5c8d3acdd03917d2d',
    messagingSenderId: '209827023192',
    projectId: 'et-si-app',
    storageBucket: 'et-si-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVh-ahC_FpTJ1xnDQyCm2HQPPkqiqq3o',
    appId: '1:209827023192:ios:07dd874072379571917d2d',
    messagingSenderId: '209827023192',
    projectId: 'et-si-app',
    storageBucket: 'et-si-app.firebasestorage.app',
    iosBundleId: 'com.etsilab.etSi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVh-ahC_FpTJ1xnDQyCm2HQPPkqiqq3o',
    appId: '1:209827023192:ios:07dd874072379571917d2d',
    messagingSenderId: '209827023192',
    projectId: 'et-si-app',
    storageBucket: 'et-si-app.firebasestorage.app',
    iosBundleId: 'com.etsilab.etSi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCo2Dc6Zw4nXJywFinu_g4xT2BKzoYHNY',
    appId: '1:209827023192:web:98495db98997c143917d2d',
    messagingSenderId: '209827023192',
    projectId: 'et-si-app',
    authDomain: 'et-si-app.firebaseapp.com',
    storageBucket: 'et-si-app.firebasestorage.app',
    measurementId: 'G-94ZDG43ZZ5',
  );
}
